# Generated by Django 2.2.19 on 2024-06-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id объявления')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок объявления')),
                ('viewers', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('position', models.PositiveSmallIntegerField(verbose_name='позиция объявления в ленте')),
            ],
        ),
    ]
